---
title: "ESM 244 - Lab Week 2"
author: "Indigo Bannister"
date: "1/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# for general data wrangling
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

# for PCA
library(ggfortify)

# for ggplot customization
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

# for compound figures
library(patchwork)
```

## Part 1: PCA with penguins

```{r}
penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>% 
  drop_na() %>% 
  scale() %>% 
  prcomp()

penguin_pca$rotation
# can add $ after list to see what can call within list (eg "penguin_pca$")

# Create another dataset that matches that used in pca to make plots more customizable
penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm"))

# use autoplot to automatically plot biplot with pca dataset; can use all ggplot codes with autoplot (see Allisons code_key for more options)
autoplot(penguin_pca, 
         data = penguin_complete,
         colour = 'species',
         loadings = TRUE,
         loadings.label = TRUE) + 
  theme_minimal()
  
```

## Part 2: ggplot2 customization & reading in different file types

First, read in an .xlsx file and do some wrangling

```{r}
fish_noaa <- read_excel(here("data","foss_landings.xlsx")) %>% 
  clean_names() %>% 
  mutate(across(where(is.character), tolower)) %>% 
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>% 
  filter(confidentiality == 'public')
```

Make a customized graph

```{r}
fish_plot <- ggplot(data = fish_noaa, aes(x = year, y = pounds)) + 
  geom_line(aes(color = nmfs_name), show.legend = FALSE) +
  theme_minimal()

fish_plot

# use plotly to make an interactive graph

ggplotly(fish_plot)

# Use gghighlight to highlight certain series
ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) + 
  geom_line() +
  theme_minimal() +
  gghighlight(nmfs_name == "tunas")

ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) + 
  geom_line(aes(color = nmfs_name)) +
  theme_minimal() +
  gghighlight(max(pounds) > 1e8)

```

